### ISSUE TITLE
홈페이지 하단 정보

### ISSUE THREAD

**Issue by makerspace-we** [makerspacewe/makerspacewe.github.io#13]
상호 : 우리문고  |  대표자 : 이병길  |  충청북도 청주시 상당구 상당로 59번길 15 (남문로 2가 48-16)  |  이메일 : dcmsw@naver.com

사업자등록번호 : 317-81-32466 [사업자정보확인]  |  통신판매업신고 :제 2019-충북청주-1608 호  |  개인정보보호책임자 : 이병길  |  입금계좌 : 신한은행 100-033-878767 (주)우리문고 이병길

**Comment by diginori** [comment]
![image](https://user-images.githubusercontent.com/2715168/69928817-3749fb00-1500-11ea-8b7e-fbbeb5323224.png)

49cfd7d..b7f4928  master -> master 반영 완료
